{
 "title": "Server Environment",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Door Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "burtonr_server_room_status{name=\"Door\"}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "description": "Showing the temperature of all the sensors connected",
   "gridPos": { "h": 10, "w": 14, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "burtonr_server_room_temperature",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Current Temperature",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(burtonr_server_room_temperature)"
    }
   ]
  },
  {
   "title": "Current Humidity",
   "type": "stat",
   "description": "Reading of the last humidity value received",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "burtonr_server_room_humidity" }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "description": "Humidity level in percentage",
   "gridPos": { "h": 11, "w": 14, "x": 4, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "burtonr_server_room_humidity", "legendFormat": "Humidity" }
   ]
  }
 ]
}