apiVersion: v1
kind: Endpoints
metadata:
  name: rpi-metrics
  labels:
    k8s-app: rpi-metrics
subsets:
  - addresses:
      - ip: 192.168.0.76
    ports:
      - name: metrics
        port: 8888
        protocol: TCP