apiVersion: v1
kind: Service
metadata:
  name: rpi-metrics
  namespace: monitoring
  labels:
    k8s-app: rpi-metrics
spec:
  type: ExternalName
  externalName: 192.168.0.76
  clusterIP: ""
  ports:
  - name: metrics
    port: 8888
    protocol: TCP
    targetPort: 8888
